### ISSUE TITLE
Index.html not being created during npm run build step

### ISSUE THREAD

**Issue by devdog66** [MatthiesenXYZ/astro-ghostcms#140]
First, excellent project here.  When running npm run build and then npm run preview, there is no resource created for / resulting in 404 page showing in browsers.

Any known path always results in the 404 page.

 - OS: Everything is a VirtualBox Guest, Windows 11 for running the project , Ubuntu 20 for Ghost instance, Debian for MariaDB.
 - Browsers Chrome, Firefox, Falkon(with javascript disabled) 
 - Version

**Additional context**
Also, I used the manual method to install this fine tool, although, I installed it over an existing Astro project with basic html content.

Here is my package.json
{
  "name": "static-app",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "deploy": "shx cp -r dist/* ../client-app/public",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.7.0",
    "@matthiesenxyz/astro-ghostcms": "^3.3.5",
    "astro": "^4.9.1",
    "typescript": "^5.4.5"
  },
  "devDependencies": {
    "shx": "^0.3.4"
  }
}

astro.config.mjs
import { defineConfig } from 'astro/config';
import astroGhostCMS from '@matthiesenxyz/astro-ghostcms';

// https://astro.build/config
export default defineConfig({
    server: {
      host: "127.0.0.1",
      port: 8088
    },
    site: 'https://example.com',
    integrations: [
      astroGhostCMS({
        // `ghostURL` Recommended to set here, Can also set in .env as CONTENT_API_URL
        ghostURL: "http://ghostcms.meikos.internal",
      })
    ]
  });

**Comment by Adammatthiesen** [comment]
Sorry about the delay, been working hard on the `@astrolicious/studiocms` project :sweat_smile:

 have you set your CONTENT_API_KEY? as per [these docs](https://astro-ghostcms.xyz/intro/integration-mode/manual/#install) ?

Also please note, that Astro-GhostCMS by default will auto inject the default theme into the default route: `/` also known as the baseroute, so if you have any files in your `/src/pages/` that conflict with this that could also cause the issue of things not working.

if you could, please enable verbose mode and provide the log output from Astro startup.

**Comment by Adammatthiesen** [comment]
I will also note, that i also just noticed my personal ghost server has gone offline... i will work to bring that back online, so i can update and refactor the ghostCMS package to the most recent versions of astro, as this project has fallen behind in its updates :sweat_smile: this is primarily due to the fact that I have been focused on my being a part of the [`StudioCMS`](https://github.com/astrolicious/studiocms) project, and getting it up and running!

**Comment by Adammatthiesen** [comment]
> Branch [issue-140-Index_html_not_being_created_dur](https://github.com/MatthiesenXYZ/astro-ghostcms/tree/issue-140-Index_html_not_being_created_dur) created!

Eh... right.... i forgot about you... bad bot...

**Comment by devdog66** [comment]
No worries. 

 

I was able to code an importer script myself that just pulls in posts and pages from Ghost. I used some of the code from your repo to get me a head start on that.  Thank you again for sharing your awesome work. 

 

My needs are not as extensive as what you are doing with the astro-ghostcms project. 

 

I will have to check out studio CMS.

 

Thanks again

Mike
